export const translations = {
    tr: {
        header: "What To Doodle",
        completedTitle: "Tamamlanan Hedefler",
        emptyWarn: "Lütfen bir hedef giriniz! ⚠️",
        deleteConfirm: "Bu hedefi silmek istediğinize emin misiniz? 🗑️",
        confirmAllDelete: "Tüm hedefleri silmek istediğinize emin misiniz? 🗑️",
        confirmArchive: "Tamamlanan tüm hedefleri arşive taşımak istiyor musunuz? 📦",
        addSuccess: "Hedef başarıyla eklendi! 🚀",
        deleteSuccess: "Hedef silindi.",
        undo: "Geri al",
        undoSuccess: "Hedef geri yüklendi.",
        updateSuccess: "Hedefiniz güncellendi! ✅",
        updateWarn: "Görev içeriği boş bırakılamaz! ⚠️",
        congrats: "Tebrikler hedefinizi tamamladınız! 😊",
        noTodos: "Henüz bir hedefiniz yok. Hadi bir tane ekleyin! ✨",
        footerText: "Designed & Developed by",
        placeholder: "Bir hedef giriniz...",
        buttonText: "HEDEF EKLE",
        all: "Hepsi",
        active: "Yapılacaklar",
        completed: "Tamamlananlar",
        archive: "Arşiv",
        clearAll: "Tümünü Sil",
        clearCompleted: "Tamamlananları Arşivle",
        progressText: "İlerleme Durumu",
        progressCompleted: "Tamamlanan",
        settings: "Ayarlar",
        soundEffects: "Ses Efektleri",
        loading: "Lütfen bekleyin...",
        archiveTitle: "Arşivlenmiş hedefler burada saklanır.",
        archiveEmpty: "Arşiviniz şu an boş. 📭",
        languageLabel: "Dil",
        linkGoogle: "Hesabı Google'a Bağla",
        logout: "Oturumu Kapat",
        loginMethodText: "Hedeflerinize ulaşmak için bir yöntem seçin",
        google: "Google",
        guest: "Misafir",
        authSuccess: "Giriş başarılı!",
        loginError: "Giriş başarısız!",
        guestStarted: "Misafir oturumu açıldı.",
        guestRestored: "Eski oturumunuz yüklendi.",
        guestUpgradeWarning: "Hedeflerinizin kaybolmaması için lütfen bir hesap bağlayın.",
        accountLinked: "Hesabınız bağlandı!",
        accountExistsTitle: "Hesap Zaten Var",
        accountExistsText: "Bu Google hesabı zaten başka bir kullanıcıya bağlı.",
        logoutTitle: "Oturumu Kapat",
        logoutQuestion: "Verileriniz silinsin mi?",
        logoutConfirmDelete: "Hepsini Sil",
        logoutCancelKeep: "Verilerimi Sakla",
        loggedOut: "Çıkış yapıldı.",
        dataCleared: "Veriler temizlendi.",
        dataSaved: "Verileriniz saklandı.",
        confirmDeleteYes: "Evet, sil!",
        archiveCompletedInfo: "Tamamlananlar arşivlendi.",
        restoreInfo: "Hedef arşivden geri alındı.",
        noArchivableSelected: "Seçili görevler arasında arşivlenecek tamamlanmış görev yok.",
        noDeletableTodos: "Silinecek aktif bir hedef yok.",
        confirmSelectedDelete: "Seçili hedefleri silmek istediğinize emin misiniz? 🗑️",
        selectionMode: "Seçim Modu",
        selectionModeOff: "Seçim Modunu Kapat",
        archiveSelected: "Seçilenleri Arşivle",
        completeSelected: "Seçilenleri Tamamla",
        deleteSelected: "Seçilenleri Sil",
        selectedLabel: "Seçilenler:",
        selectAll: "Tümünü Seç",
        deadline: "Son tarih",
        deadlinePlaceholder: "Tarih ve saat seçin (opsiyonel)",
        noDeadline: "Temizle",
        timeLabel: "Saat",
        close: "Kapat",
        back: "Geri",
        editActionsLabel: "İşlemler",
        saveTask: "Kaydet",
        deleteTask: "Sil",
        cancelEdit: "Vazgeç",
        selectedTimeLabel: "Seçilen:",
        customTimeLabel: "Özel saat",
        hourLabel: "Saat",
        minuteLabel: "Dakika",
        applyTime: "Uygula",
        confirm: "Onayla",
        completedAt: "Tamamlanma tarihi"
    },
    fr: {
        header: "What To Doodle",
        completedTitle: "Tâches terminées",
        emptyWarn: "Veuillez saisir une tâche ! ⚠️",
        deleteConfirm: "Voulez-vous vraiment supprimer cette tâche ? 🗑️",
        confirmAllDelete: "Voulez-vous vraiment supprimer toutes les tâches ? 🗑️",
        confirmArchive: "Voulez-vous déplacer toutes les tâches terminées vers l’archive ? 📦",
        addSuccess: "Tâche ajoutée avec succès ! 🚀",
        deleteSuccess: "Tâche supprimée.",
        undo: "Annuler",
        undoSuccess: "Tâche rétablie.",
        updateSuccess: "Votre tâche a été mise à jour ! ✅",
        updateWarn: "Le contenu de la tâche ne peut pas être vide ! ⚠️",
        congrats: "Félicitations, vous avez terminé votre objectif ! 😊",
        noTodos: "Aucune tâche pour l’instant. Ajoutez-en une ! ✨",
        footerText: "Conçu & développé par",
        placeholder: "Saisissez une tâche...",
        buttonText: "AJOUTER",
        all: "Toutes",
        active: "À faire",
        completed: "Terminées",
        archive: "Archive",
        clearAll: "Tout supprimer",
        clearCompleted: "Archiver les terminées",
        progressText: "État d’avancement",
        progressCompleted: "Terminées",
        settings: "Paramètres",
        soundEffects: "Effets sonores",
        loading: "Veuillez patienter...",
        archiveTitle: "Les objectifs archivés sont stockés ici.",
        archiveEmpty: "Votre archive est vide. 📭",
        languageLabel: "Langue",
        linkGoogle: "Lier au compte Google",
        logout: "Se déconnecter",
        loginMethodText: "Choisissez une méthode",
        google: "Google",
        guest: "Invité",
        authSuccess: "Connexion réussie !",
        loginError: "Échec de la connexion !",
        guestStarted: "Session invité démarrée.",
        guestRestored: "Ancienne session restaurée.",
        guestUpgradeWarning: "Veuillez lier un compte pour éviter toute perte de données.",
        accountLinked: "Compte lié avec succès !",
        accountExistsTitle: "Compte déjà existant",
        accountExistsText: "Ce compte Google est déjà lié à un autre utilisateur.",
        logoutTitle: "Déconnexion",
        logoutQuestion: "Supprimer les données ?",
        logoutConfirmDelete: "Tout supprimer",
        logoutCancelKeep: "Conserver mes données",
        loggedOut: "Déconnecté.",
        dataCleared: "Données effacées.",
        dataSaved: "Données sauvegardées.",
        confirmDeleteYes: "Oui, supprimer !",
        archiveCompletedInfo: "Les tâches terminées ont été archivées.",
        restoreInfo: "L’objectif a été restauré depuis l’archive.",
        noArchivableSelected: "Aucune tâche terminée à archiver dans la sélection.",
        noDeletableTodos: "Aucune tâche active à supprimer.",
        confirmSelectedDelete: "Voulez-vous vraiment supprimer les tâches sélectionnées ? 🗑️",
        selectionMode: "Mode sélection",
        selectionModeOff: "Fermer le mode sélection",
        archiveSelected: "Archiver les sélectionnées",
        completeSelected: "Marquer comme terminées",
        deleteSelected: "Supprimer les sélectionnées",
        selectedLabel: "Sélectionnées :",
        selectAll: "Tout sélectionner",
        deadline: "Date limite",
        deadlinePlaceholder: "Date et heure (optionnel)",
        noDeadline: "Effacer",
        timeLabel: "Heure",
        close: "Fermer",
        back: "Retour",
        editActionsLabel: "Actions",
        saveTask: "Enregistrer",
        deleteTask: "Supprimer",
        cancelEdit: "Annuler",
        selectedTimeLabel: "Choisi :",
        customTimeLabel: "Heure personnalisée",
        hourLabel: "Heure",
        minuteLabel: "Minute",
        applyTime: "Appliquer",
        confirm: "Confirmer",
        completedAt: "Date de complétion"
    },
    en: {
        header: "What To Doodle",
        completedTitle: "Completed Tasks",
        emptyWarn: "Please enter a task! ⚠️",
        deleteConfirm: "Are you sure you want to delete this task? 🗑️",
        confirmAllDelete: "Are you sure you want to delete all tasks? 🗑️",
        confirmArchive: "Do you want to move all completed tasks to archive? 📦",
        addSuccess: "Task added successfully! 🚀",
        deleteSuccess: "Task deleted.",
        undo: "Undo",
        undoSuccess: "Task restored.",
        updateSuccess: "Task updated successfully! ✅",
        updateWarn: "Task content cannot be empty! ⚠️",
        congrats: "Congratulations, you completed your goal! 😊",
        noTodos: "No tasks yet. Let's add one! ✨",
        footerText: "Designed & Developed by",
        placeholder: "Enter a task...",
        buttonText: "ADD TASK",
        all: "All",
        active: "Active",
        completed: "Completed",
        archive: "Archive",
        clearAll: "Clear All",
        clearCompleted: "Archive Completed",
        progressText: "Progress Status",
        progressCompleted: "Completed",
        settings: "Settings",
        soundEffects: "Sound Effects",
        loading: "Please wait...",
        archiveTitle: "Archived goals are stored here.",
        archiveEmpty: "Archive is empty. 📭",
        languageLabel: "Language",
        linkGoogle: "Link to Google",
        logout: "Logout",
        loginMethodText: "Choose a method",
        google: "Google",
        guest: "Guest",
        authSuccess: "Login successful!",
        loginError: "Login failed!",
        guestStarted: "Guest session started.",
        guestRestored: "Previous session restored.",
        guestUpgradeWarning: "Please link an account to prevent data loss.",
        accountLinked: "Account linked!",
        accountExistsTitle: "Account Already Exists",
        accountExistsText: "This Google account is already linked to another user.",
        logoutTitle: "Logout",
        logoutQuestion: "Delete data?",
        logoutConfirmDelete: "Delete All",
        logoutCancelKeep: "Keep My Data",
        loggedOut: "Logged out.",
        dataCleared: "Data cleared.",
        dataSaved: "Data saved.",
        confirmDeleteYes: "Yes, delete!",
        archiveCompletedInfo: "Completed archived.",
        restoreInfo: "Task has been restored from archive.",
        noArchivableSelected: "No completed tasks in the selection to archive.",
        noDeletableTodos: "There are no active tasks to delete.",
        confirmSelectedDelete: "Are you sure you want to delete selected tasks? 🗑️",
        selectionMode: "Selection Mode",
        selectionModeOff: "Exit Selection Mode",
        archiveSelected: "Archive Selected",
        completeSelected: "Complete Selected",
        deleteSelected: "Delete Selected",
        selectedLabel: "Selected:",
        selectAll: "Select All",
        deadline: "Deadline",
        deadlinePlaceholder: "Pick date & time (optional)",
        noDeadline: "Clear",
        timeLabel: "Time",
        close: "Close",
        back: "Back",
        editActionsLabel: "Actions",
        saveTask: "Save",
        deleteTask: "Delete",
        cancelEdit: "Cancel",
        selectedTimeLabel: "Selected:",
        customTimeLabel: "Custom time",
        hourLabel: "Hour",
        minuteLabel: "Min",
        applyTime: "Apply",
        confirm: "Confirm",
        completedAt: "Completion date"
    },
    sq: {
        header: "What To Doodle",
        completedTitle: "Detyrat e përfunduara",
        emptyWarn: "Ju lutemi vendosni një detyrë! ⚠️",
        deleteConfirm: "Jeni të sigurt që dëshironi ta fshini këtë detyrë? 🗑️",
        confirmAllDelete: "Jeni të sigurt që dëshironi të fshini të gjitha detyrat? 🗑️",
        confirmArchive: "Dëshironi të zhvendosni detyrat e përfunduara në arkiv? 📦",
        addSuccess: "Detyra u shtua me sukses! 🚀",
        deleteSuccess: "Detyra u fshi.",
        undo: "Rikthe",
        undoSuccess: "Detyra u rikthye.",
        updateSuccess: "Detyra juaj u përditësua! ✅",
        updateWarn: "Përmbajtja e detyrës nuk mund të jetë bosh! ⚠️",
        congrats: "Urime, e përfunduat qëllimin tuaj! 😊",
        noTodos: "Ende nuk keni detyra. Shtoni një! ✨",
        footerText: "Dizajnuar & Zhvilluar nga",
        placeholder: "Vendosni një detyrë...",
        buttonText: "SHTO DETYRË",
        all: "Të gjitha",
        active: "Për të bërë",
        completed: "Të përfunduara",
        archive: "Arkivi",
        clearAll: "Fshi të gjitha",
        clearCompleted: "Arkivo të përfunduarat",
        progressText: "Statusi i progresit",
        progressCompleted: "Përfunduar",
        settings: "Cilësimet",
        soundEffects: "Efektet zanore",
        loading: "Ju lutemi prisni...",
        archiveTitle: "Qëllimet e arkivuara ruhen këtu.",
        archiveEmpty: "Arkivi juaj është bosh. 📭",
        languageLabel: "Gjuha",
        linkGoogle: "Lidhni me llogarinë Google",
        logout: "Dilni",
        loginMethodText: "Zgjidhni një metodë",
        google: "Google",
        guest: "Vizitor",
        authSuccess: "Hyrja u krye me sukses!",
        loginError: "Hyrja dështoi!",
        guestStarted: "Sesioni i vizitorit u fillua.",
        guestRestored: "Sesioni i mëparshëm u rikthye.",
        guestUpgradeWarning: "Ju lutemi lidhni një llogari për të shmangur humbjen e të dhënave.",
        accountLinked: "Llogaria juaj u lidh!",
        accountExistsTitle: "Llogaria ekziston tashmë",
        accountExistsText: "Ky llogari Google është tashmë i lidhur me një përdorues tjetër.",
        logoutTitle: "Dilni",
        logoutQuestion: "Të fshihen të dhënat?",
        logoutConfirmDelete: "Fshi të gjitha",
        logoutCancelKeep: "Mbaj të dhënat e mia",
        loggedOut: "U dil.",
        dataCleared: "Të dhënat u pastruan.",
        dataSaved: "Të dhënat tuaja u ruajtën.",
        confirmDeleteYes: "Po, fshi!",
        archiveCompletedInfo: "Të përfunduarat u arkivuan.",
        restoreInfo: "Detyra u rikthye nga arkivi.",
        noArchivableSelected: "Nuk ka detyra të përfunduara për të arkivuar në përzgjedhje.",
        noDeletableTodos: "Nuk ka detyra aktive për të fshirë.",
        confirmSelectedDelete: "Jeni të sigurt që dëshironi të fshini detyrat e përzgjedhura? 🗑️",
        selectionMode: "Modaliteti i përzgjedhjes",
        selectionModeOff: "Mbyll modalitetin e përzgjedhjes",
        archiveSelected: "Arkivo të përzgjedhurat",
        completeSelected: "Përfundo të përzgjedhurat",
        deleteSelected: "Fshi të përzgjedhurat",
        selectedLabel: "Të përzgjedhura:",
        selectAll: "Zgjidh të gjitha",
        deadline: "Afati",
        deadlinePlaceholder: "Zgjidhni datën dhe orën (opsionale)",
        noDeadline: "Pastro",
        timeLabel: "Koha",
        close: "Mbyll",
        back: "Mbrapa",
        editActionsLabel: "Veprimet",
        saveTask: "Ruaj",
        deleteTask: "Fshi",
        cancelEdit: "Anulo",
        selectedTimeLabel: "E zgjedhur:",
        customTimeLabel: "Orë e personalizuar",
        hourLabel: "Ora",
        minuteLabel: "Minuta",
        applyTime: "Apliko",
        confirm: "Konfirmo",
        completedAt: "Data e përfundimit"
    }
};