export const translations = {
    tr: {
        header: "To-Do Lıst",
        completedTitle: "Tamamlanan Hedefler",
        emptyWarn: "Lütfen bir hedef giriniz! ⚠️",
        deleteConfirm: "Bu hedefi silmek istediğinize emin misiniz? 🗑️",
        confirmAllDelete: "Tüm hedefleri silmek istediğinize emin misiniz? 🗑️",
        confirmArchive: "Tamamlanan tüm hedefleri arşive taşımak istiyor musunuz? 📦",
        addSuccess: "Hedef başarıyla eklendi! 🚀",
        deleteSuccess: "Hedef başarıyla silindi! 🗑️",
        updateSuccess: "Hedefiniz güncellendi! ✅",
        updateWarn: "Görev içeriği boş bırakılamaz! ⚠️",
        congrats: "Tebrikler hedefinizi tamamladınız! 😊",
        noTodos: "Henüz bir hedefiniz yok. Hadi bir tane ekleyin! ✨",
        footerText: "Designed & Developed by",
        placeholder: "Bir hedef giriniz...",
        buttonText: "HEDEF EKLE",
        all: "Hepsi",
        active: "Yapılacaklar",
        completed: "Tamamlananlar",
        archive: "Arşiv",
        clearAll: "Tümünü Sil",
        clearCompleted: "Tamamlananları Arşivle",
        progressText: "İlerleme Durumu",
        progressCompleted: "Tamamlanan",
        settings: "Ayarlar",
        soundEffects: "Ses Efektleri",
        loading: "Lütfen bekleyin...",
        archiveTitle: "Arşivlenmiş hedefler burada saklanır.",
        archiveEmpty: "Arşiviniz şu an boş. 📭",
        languageLabel: "Dil",
        linkGoogle: "Hesabı Google'a Bağla",
        logout: "Oturumu Kapat",
        loginMethodText: "Hedeflerinize ulaşmak için bir yöntem seçin",
        google: "Google",
        guest: "Misafir",
        authSuccess: "Giriş başarılı!",
        loginError: "Giriş başarısız!",
        guestStarted: "Misafir oturumu açıldı.",
        guestRestored: "Eski oturumunuz yüklendi.",
        guestUpgradeWarning: "Hedeflerinizin kaybolmaması için lütfen bir hesap bağlayın.",
        accountLinked: "Hesabınız bağlandı!",
        accountExistsTitle: "Hesap Zaten Var",
        accountExistsText: "Bu Google hesabı zaten başka bir kullanıcıya bağlı.",
        logoutTitle: "Oturumu Kapat",
        logoutQuestion: "Verileriniz silinsin mi?",
        logoutConfirmDelete: "Hepsini Sil",
        logoutCancelKeep: "Verilerimi Sakla",
        loggedOut: "Çıkış yapıldı.",
        dataCleared: "Veriler temizlendi.",
        dataSaved: "Verileriniz saklandı.",
        confirmDeleteYes: "Evet, sil!",
        archiveCompletedInfo: "Tamamlananlar arşivlendi."
    },
    en: {
        header: "To-Do Lıst",
        completedTitle: "Completed Tasks",
        emptyWarn: "Please enter a task! ⚠️",
        deleteConfirm: "Are you sure you want to delete this task? 🗑️",
        confirmAllDelete: "Are you sure you want to delete all tasks? 🗑️",
        confirmArchive: "Do you want to move all completed tasks to archive? 📦",
        addSuccess: "Task added successfully! 🚀",
        deleteSuccess: "Task deleted successfully! 🗑️",
        updateSuccess: "Task updated successfully! ✅",
        updateWarn: "Task content cannot be empty! ⚠️",
        congrats: "Congratulations, you completed your goal! 😊",
        noTodos: "No tasks yet. Let's add one! ✨",
        footerText: "Designed & Developed by",
        placeholder: "Enter a task...",
        buttonText: "ADD TASK",
        all: "All",
        active: "Active",
        completed: "Completed",
        archive: "Archive",
        clearAll: "Clear All",
        clearCompleted: "Archive Completed",
        progressText: "Progress Status",
        progressCompleted: "Completed",
        settings: "Settings",
        soundEffects: "Sound Effects",
        loading: "Please wait...",
        archiveTitle: "Archived goals are stored here.",
        archiveEmpty: "Archive is empty. 📭",
        languageLabel: "Language",
        linkGoogle: "Link to Google",
        logout: "Logout",
        loginMethodText: "Choose a method",
        google: "Google",
        guest: "Guest",
        authSuccess: "Login successful!",
        loginError: "Login failed!",
        guestStarted: "Guest session started.",
        guestRestored: "Previous session restored.",
        guestUpgradeWarning: "Please link an account to prevent data loss.",
        accountLinked: "Account linked!",
        accountExistsTitle: "Account Already Exists",
        accountExistsText: "This Google account is already linked to another user.",
        logoutTitle: "Logout",
        logoutQuestion: "Delete data?",
        logoutConfirmDelete: "Delete All",
        logoutCancelKeep: "Keep My Data",
        loggedOut: "Logged out.",
        dataCleared: "Data cleared.",
        dataSaved: "Data saved.",
        confirmDeleteYes: "Yes, delete!",
        archiveCompletedInfo: "Completed archived."
    }
};