export const translations = {
    tr: {
        header: "To-Do Lıst",
        completedTitle: "Tamamlanan Hedefler",
        emptyWarn: "Lütfen bir hedef giriniz! ⚠️",
        deleteConfirm: "Bu hedefi silmek istediğinize emin misiniz? 🗑️",
        confirmAllDelete: "Tüm hedefleri silmek istediğinize emin misiniz? 🗑️",
        confirmArchive: "Tamamlanan tüm hedefleri arşive taşımak istiyor musunuz? 📦",
        addSuccess: "Hedef başarıyla eklendi! 🚀",
        deleteSuccess: "Hedef başarıyla silindi! 🗑️",
        updateSuccess: "Hedefiniz güncellendi! ✅",
        updateWarn: "Görev içeriği boş bırakılamaz! ⚠️",
        congrats: "Tebrikler hedefinizi tamamladınız! 😊",
        noTodos: "Henüz bir hedefiniz yok. Hadi bir tane ekleyin! ✨",
        footerText: "Designed & Developed by",
        placeholder: "Bir hedef giriniz...",
        buttonText: "HEDEF EKLE",
        all: "Hepsi",
        active: "Yapılacaklar",
        completed: "Tamamlananlar",
        archive: "Arşiv",
        clearAll: "Tümünü Sil",
        clearCompleted: "Tamamlananları Arşivle",
        progressText: "İlerleme Durumu",
        progressCompleted: "Tamamlanan",
        settings: "Ayarlar",
        soundEffects: "Ses Efektleri",
        loading: "Lütfen bekleyin...",
        archiveTitle: "Arşivlenmiş hedefler burada saklanır.",
        archiveEmpty: "Arşiviniz şu an boş. 📭",
        languageLabel: "Dil",
        linkGoogle: "Hesabı Google'a Bağla",
        logout: "Oturumu Kapat",
        loginMethodText: "Hedeflerinize ulaşmak için bir yöntem seçin",
        google: "Google",
        guest: "Misafir",
        authSuccess: "Giriş başarılı!",
        loginError: "Giriş başarısız!",
        guestStarted: "Misafir oturumu açıldı.",
        guestRestored: "Eski oturumunuz yüklendi.",
        guestUpgradeWarning: "Hedeflerinizin kaybolmaması için lütfen bir hesap bağlayın.",
        accountLinked: "Hesabınız bağlandı!",
        accountExistsTitle: "Hesap Zaten Var",
        accountExistsText: "Bu Google hesabı zaten başka bir kullanıcıya bağlı.",
        logoutTitle: "Oturumu Kapat",
        logoutQuestion: "Verileriniz silinsin mi?",
        logoutConfirmDelete: "Hepsini Sil",
        logoutCancelKeep: "Verilerimi Sakla",
        loggedOut: "Çıkış yapıldı.",
        dataCleared: "Veriler temizlendi.",
        dataSaved: "Verileriniz saklandı.",
        confirmDeleteYes: "Evet, sil!",
        archiveCompletedInfo: "Tamamlananlar arşivlendi.",
        noArchivableSelected: "Seçili görevler arasında arşivlenecek tamamlanmış görev yok.",
        confirmSelectedDelete: "Seçili hedefleri silmek istediğinize emin misiniz? 🗑️",
        selectionMode: "Seçim Modu",
        selectionModeOff: "Seçim Modunu Kapat",
        archiveSelected: "Seçilenleri Arşivle",
        completeSelected: "Seçilenleri Tamamla",
        deleteSelected: "Seçilenleri Sil",
        selectedLabel: "Seçilenler:",
        selectAll: "Tümünü Seç"
    },
    fr: {
        header: "Liste de tâches",
        completedTitle: "Tâches terminées",
        emptyWarn: "Veuillez saisir une tâche ! ⚠️",
        deleteConfirm: "Voulez-vous vraiment supprimer cette tâche ? 🗑️",
        confirmAllDelete: "Voulez-vous vraiment supprimer toutes les tâches ? 🗑️",
        confirmArchive: "Voulez-vous déplacer toutes les tâches terminées vers l’archive ? 📦",
        addSuccess: "Tâche ajoutée avec succès ! 🚀",
        deleteSuccess: "Tâche supprimée avec succès ! 🗑️",
        updateSuccess: "Votre tâche a été mise à jour ! ✅",
        updateWarn: "Le contenu de la tâche ne peut pas être vide ! ⚠️",
        congrats: "Félicitations, vous avez terminé votre objectif ! 😊",
        noTodos: "Aucune tâche pour l’instant. Ajoutez-en une ! ✨",
        footerText: "Conçu & développé par",
        placeholder: "Saisissez une tâche...",
        buttonText: "AJOUTER",
        all: "Toutes",
        active: "À faire",
        completed: "Terminées",
        archive: "Archive",
        clearAll: "Tout supprimer",
        clearCompleted: "Archiver les terminées",
        progressText: "État d’avancement",
        progressCompleted: "Terminées",
        settings: "Paramètres",
        soundEffects: "Effets sonores",
        loading: "Veuillez patienter...",
        archiveTitle: "Les objectifs archivés sont stockés ici.",
        archiveEmpty: "Votre archive est vide. 📭",
        languageLabel: "Langue",
        linkGoogle: "Lier au compte Google",
        logout: "Se déconnecter",
        loginMethodText: "Choisissez une méthode",
        google: "Google",
        guest: "Invité",
        authSuccess: "Connexion réussie !",
        loginError: "Échec de la connexion !",
        guestStarted: "Session invité démarrée.",
        guestRestored: "Ancienne session restaurée.",
        guestUpgradeWarning: "Veuillez lier un compte pour éviter toute perte de données.",
        accountLinked: "Compte lié avec succès !",
        accountExistsTitle: "Compte déjà existant",
        accountExistsText: "Ce compte Google est déjà lié à un autre utilisateur.",
        logoutTitle: "Déconnexion",
        logoutQuestion: "Supprimer les données ?",
        logoutConfirmDelete: "Tout supprimer",
        logoutCancelKeep: "Conserver mes données",
        loggedOut: "Déconnecté.",
        dataCleared: "Données effacées.",
        dataSaved: "Données sauvegardées.",
        confirmDeleteYes: "Oui, supprimer !",
        archiveCompletedInfo: "Les tâches terminées ont été archivées.",
        noArchivableSelected: "Aucune tâche terminée à archiver dans la sélection.",
        confirmSelectedDelete: "Voulez-vous vraiment supprimer les tâches sélectionnées ? 🗑️",
        selectionMode: "Mode sélection",
        selectionModeOff: "Fermer le mode sélection",
        archiveSelected: "Archiver les sélectionnées",
        completeSelected: "Marquer comme terminées",
        deleteSelected: "Supprimer les sélectionnées",
        selectedLabel: "Sélectionnées :",
        selectAll: "Tout sélectionner"
    },
    en: {
        header: "To-Do Lıst",
        completedTitle: "Completed Tasks",
        emptyWarn: "Please enter a task! ⚠️",
        deleteConfirm: "Are you sure you want to delete this task? 🗑️",
        confirmAllDelete: "Are you sure you want to delete all tasks? 🗑️",
        confirmArchive: "Do you want to move all completed tasks to archive? 📦",
        addSuccess: "Task added successfully! 🚀",
        deleteSuccess: "Task deleted successfully! 🗑️",
        updateSuccess: "Task updated successfully! ✅",
        updateWarn: "Task content cannot be empty! ⚠️",
        congrats: "Congratulations, you completed your goal! 😊",
        noTodos: "No tasks yet. Let's add one! ✨",
        footerText: "Designed & Developed by",
        placeholder: "Enter a task...",
        buttonText: "ADD TASK",
        all: "All",
        active: "Active",
        completed: "Completed",
        archive: "Archive",
        clearAll: "Clear All",
        clearCompleted: "Archive Completed",
        progressText: "Progress Status",
        progressCompleted: "Completed",
        settings: "Settings",
        soundEffects: "Sound Effects",
        loading: "Please wait...",
        archiveTitle: "Archived goals are stored here.",
        archiveEmpty: "Archive is empty. 📭",
        languageLabel: "Language",
        linkGoogle: "Link to Google",
        logout: "Logout",
        loginMethodText: "Choose a method",
        google: "Google",
        guest: "Guest",
        authSuccess: "Login successful!",
        loginError: "Login failed!",
        guestStarted: "Guest session started.",
        guestRestored: "Previous session restored.",
        guestUpgradeWarning: "Please link an account to prevent data loss.",
        accountLinked: "Account linked!",
        accountExistsTitle: "Account Already Exists",
        accountExistsText: "This Google account is already linked to another user.",
        logoutTitle: "Logout",
        logoutQuestion: "Delete data?",
        logoutConfirmDelete: "Delete All",
        logoutCancelKeep: "Keep My Data",
        loggedOut: "Logged out.",
        dataCleared: "Data cleared.",
        dataSaved: "Data saved.",
        confirmDeleteYes: "Yes, delete!",
        archiveCompletedInfo: "Completed archived.",
        noArchivableSelected: "No completed tasks in the selection to archive.",
        confirmSelectedDelete: "Are you sure you want to delete selected tasks? 🗑️",
        selectionMode: "Selection Mode",
        selectionModeOff: "Exit Selection Mode",
        archiveSelected: "Archive Selected",
        completeSelected: "Complete Selected",
        deleteSelected: "Delete Selected",
        selectedLabel: "Selected:",
        selectAll: "Select All"
    }
};